# Configuration
# ----------------------- #

# Where things are
root: /
permalink: /:title

plugins: plugins    
category_dir: categories
tag_dir: tags

date_format: "ordinal"

sass:
    sass_dir: _sass
    style: :compressed

# Handling Reading
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 's3_website.yml', 'Rakefile', 'vendor', 'Procfile']

# Outputting
url: "http://schipperius.org" # the base hostname & protocol for your site
title: the Nature of Things
subtitle: an exploration of the natural world via patterns, structures, processes and such
author: Mark Schipper
simple_search: https://www.google.com/search
description: the Nature of Things; an exploration of the natural world via patterns, structures, processes and such

gems: ['jekyll/scholar']

scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
  note: